/*
 * Automatically generated by "tools/bmp_image"
 *
 * DO NOT EDIT
 *
 */


#ifndef __BMP_IMAGE_DATA_H__
#define __BMP_IMAGE_DATA_H__

#include <bmp_image.h>

bmp_image_t bmp_images[] = 
{
    {
        .offset = 0, //logos/charge/fail.bmp
        .size   = 44,
        .level  = 0,
        .loaded = 0,
    },
    {
        .offset = 44, //logos/charge/level_0/s1_001.bmp
        .size   = 36,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 80, //logos/charge/level_0/s1_002.bmp
        .size   = 35,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 115, //logos/charge/level_0/s1_003.bmp
        .size   = 49,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 164, //logos/charge/level_0/s1_004.bmp
        .size   = 45,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 209, //logos/charge/level_0/s1_005.bmp
        .size   = 45,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 254, //logos/charge/level_0/s1_006.bmp
        .size   = 47,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 301, //logos/charge/level_0/s1_007.bmp
        .size   = 43,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 344, //logos/charge/level_0/s1_008.bmp
        .size   = 47,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 391, //logos/charge/level_0/s1_009.bmp
        .size   = 50,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 441, //logos/charge/level_0/s1_010.bmp
        .size   = 52,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 493, //logos/charge/level_0/s1_011.bmp
        .size   = 54,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 547, //logos/charge/level_0/s1_012.bmp
        .size   = 56,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 603, //logos/charge/level_0/s1_013.bmp
        .size   = 58,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 661, //logos/charge/level_0/s1_014.bmp
        .size   = 58,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 719, //logos/charge/level_0/s1_015.bmp
        .size   = 58,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 777, //logos/charge/level_0/s1_016.bmp
        .size   = 60,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 837, //logos/charge/level_0/s1_017.bmp
        .size   = 61,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 898, //logos/charge/level_0/s1_018.bmp
        .size   = 60,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 958, //logos/charge/level_0/s1_019.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1024, //logos/charge/level_0/s1_020.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1090, //logos/charge/level_0/s1_021.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1156, //logos/charge/level_0/s1_022.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1222, //logos/charge/level_0/s1_023.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1288, //logos/charge/level_0/s1_024.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1354, //logos/charge/level_0/s1_025.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1420, //logos/charge/level_0/s1_026.bmp
        .size   = 66,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1486, //logos/charge/level_0/s1_027.bmp
        .size   = 61,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1547, //logos/charge/level_0/s1_028.bmp
        .size   = 64,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1611, //logos/charge/level_0/s1_029.bmp
        .size   = 63,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1674, //logos/charge/level_0/s1_030.bmp
        .size   = 56,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1730, //logos/charge/level_0/s1_031.bmp
        .size   = 55,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1785, //logos/charge/level_0/s1_032.bmp
        .size   = 57,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1842, //logos/charge/level_0/s1_033.bmp
        .size   = 52,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1894, //logos/charge/level_0/s1_034.bmp
        .size   = 52,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 1946, //logos/charge/level_0/s1_035.bmp
        .size   = 57,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2003, //logos/charge/level_0/s1_036.bmp
        .size   = 52,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2055, //logos/charge/level_0/s1_037.bmp
        .size   = 49,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2104, //logos/charge/level_0/s1_038.bmp
        .size   = 44,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2148, //logos/charge/level_0/s1_039.bmp
        .size   = 45,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2193, //logos/charge/level_0/s1_040.bmp
        .size   = 47,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2240, //logos/charge/level_0/s1_041.bmp
        .size   = 47,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2287, //logos/charge/level_0/s1_042.bmp
        .size   = 52,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2339, //logos/charge/level_0/s1_043.bmp
        .size   = 33,
        .level  = 1,
        .loaded = 0,
    },
    {
        .offset = 2372, //logos/charge/level_1/s2_001.bmp
        .size   = 40,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2412, //logos/charge/level_1/s2_002.bmp
        .size   = 39,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2451, //logos/charge/level_1/s2_003.bmp
        .size   = 52,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2503, //logos/charge/level_1/s2_004.bmp
        .size   = 48,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2551, //logos/charge/level_1/s2_005.bmp
        .size   = 48,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2599, //logos/charge/level_1/s2_006.bmp
        .size   = 50,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2649, //logos/charge/level_1/s2_007.bmp
        .size   = 47,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2696, //logos/charge/level_1/s2_008.bmp
        .size   = 50,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2746, //logos/charge/level_1/s2_009.bmp
        .size   = 53,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2799, //logos/charge/level_1/s2_010.bmp
        .size   = 53,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2852, //logos/charge/level_1/s2_011.bmp
        .size   = 56,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2908, //logos/charge/level_1/s2_012.bmp
        .size   = 58,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 2966, //logos/charge/level_1/s2_013.bmp
        .size   = 59,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3025, //logos/charge/level_1/s2_014.bmp
        .size   = 59,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3084, //logos/charge/level_1/s2_015.bmp
        .size   = 59,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3143, //logos/charge/level_1/s2_016.bmp
        .size   = 62,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3205, //logos/charge/level_1/s2_017.bmp
        .size   = 63,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3268, //logos/charge/level_1/s2_018.bmp
        .size   = 61,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3329, //logos/charge/level_1/s2_019.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3396, //logos/charge/level_1/s2_020.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3463, //logos/charge/level_1/s2_021.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3530, //logos/charge/level_1/s2_022.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3597, //logos/charge/level_1/s2_023.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3664, //logos/charge/level_1/s2_024.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3731, //logos/charge/level_1/s2_025.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3798, //logos/charge/level_1/s2_026.bmp
        .size   = 67,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3865, //logos/charge/level_1/s2_027.bmp
        .size   = 63,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3928, //logos/charge/level_1/s2_028.bmp
        .size   = 65,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 3993, //logos/charge/level_1/s2_029.bmp
        .size   = 64,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4057, //logos/charge/level_1/s2_030.bmp
        .size   = 58,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4115, //logos/charge/level_1/s2_031.bmp
        .size   = 57,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4172, //logos/charge/level_1/s2_032.bmp
        .size   = 59,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4231, //logos/charge/level_1/s2_033.bmp
        .size   = 54,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4285, //logos/charge/level_1/s2_034.bmp
        .size   = 54,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4339, //logos/charge/level_1/s2_035.bmp
        .size   = 59,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4398, //logos/charge/level_1/s2_036.bmp
        .size   = 55,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4453, //logos/charge/level_1/s2_037.bmp
        .size   = 51,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4504, //logos/charge/level_1/s2_038.bmp
        .size   = 47,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4551, //logos/charge/level_1/s2_039.bmp
        .size   = 48,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4599, //logos/charge/level_1/s2_040.bmp
        .size   = 50,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4649, //logos/charge/level_1/s2_041.bmp
        .size   = 50,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4699, //logos/charge/level_1/s2_042.bmp
        .size   = 55,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4754, //logos/charge/level_1/s2_043.bmp
        .size   = 38,
        .level  = 3,
        .loaded = 0,
    },
    {
        .offset = 4792, //logos/charge/level_2/s3_001.bmp
        .size   = 43,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 4835, //logos/charge/level_2/s3_002.bmp
        .size   = 42,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 4877, //logos/charge/level_2/s3_003.bmp
        .size   = 54,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 4931, //logos/charge/level_2/s3_004.bmp
        .size   = 50,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 4981, //logos/charge/level_2/s3_005.bmp
        .size   = 50,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5031, //logos/charge/level_2/s3_006.bmp
        .size   = 51,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5082, //logos/charge/level_2/s3_007.bmp
        .size   = 50,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5132, //logos/charge/level_2/s3_008.bmp
        .size   = 54,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5186, //logos/charge/level_2/s3_009.bmp
        .size   = 55,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5241, //logos/charge/level_2/s3_010.bmp
        .size   = 55,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5296, //logos/charge/level_2/s3_011.bmp
        .size   = 58,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5354, //logos/charge/level_2/s3_012.bmp
        .size   = 60,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5414, //logos/charge/level_2/s3_013.bmp
        .size   = 61,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5475, //logos/charge/level_2/s3_014.bmp
        .size   = 62,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5537, //logos/charge/level_2/s3_015.bmp
        .size   = 61,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5598, //logos/charge/level_2/s3_016.bmp
        .size   = 65,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5663, //logos/charge/level_2/s3_017.bmp
        .size   = 66,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5729, //logos/charge/level_2/s3_018.bmp
        .size   = 64,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5793, //logos/charge/level_2/s3_019.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5862, //logos/charge/level_2/s3_020.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 5931, //logos/charge/level_2/s3_021.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6000, //logos/charge/level_2/s3_022.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6069, //logos/charge/level_2/s3_023.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6138, //logos/charge/level_2/s3_024.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6207, //logos/charge/level_2/s3_025.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6276, //logos/charge/level_2/s3_026.bmp
        .size   = 69,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6345, //logos/charge/level_2/s3_027.bmp
        .size   = 65,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6410, //logos/charge/level_2/s3_028.bmp
        .size   = 67,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6477, //logos/charge/level_2/s3_029.bmp
        .size   = 65,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6542, //logos/charge/level_2/s3_030.bmp
        .size   = 61,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6603, //logos/charge/level_2/s3_031.bmp
        .size   = 60,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6663, //logos/charge/level_2/s3_032.bmp
        .size   = 63,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6726, //logos/charge/level_2/s3_033.bmp
        .size   = 58,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6784, //logos/charge/level_2/s3_034.bmp
        .size   = 58,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6842, //logos/charge/level_2/s3_035.bmp
        .size   = 61,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6903, //logos/charge/level_2/s3_036.bmp
        .size   = 57,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 6960, //logos/charge/level_2/s3_037.bmp
        .size   = 55,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7015, //logos/charge/level_2/s3_038.bmp
        .size   = 49,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7064, //logos/charge/level_2/s3_039.bmp
        .size   = 49,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7113, //logos/charge/level_2/s3_040.bmp
        .size   = 51,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7164, //logos/charge/level_2/s3_041.bmp
        .size   = 51,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7215, //logos/charge/level_2/s3_042.bmp
        .size   = 56,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7271, //logos/charge/level_2/s3_043.bmp
        .size   = 40,
        .level  = 36,
        .loaded = 0,
    },
    {
        .offset = 7311, //logos/charge/level_3/s4_001.bmp
        .size   = 46,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7357, //logos/charge/level_3/s4_002.bmp
        .size   = 46,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7403, //logos/charge/level_3/s4_003.bmp
        .size   = 56,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7459, //logos/charge/level_3/s4_004.bmp
        .size   = 53,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7512, //logos/charge/level_3/s4_005.bmp
        .size   = 54,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7566, //logos/charge/level_3/s4_006.bmp
        .size   = 53,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7619, //logos/charge/level_3/s4_007.bmp
        .size   = 53,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7672, //logos/charge/level_3/s4_008.bmp
        .size   = 56,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7728, //logos/charge/level_3/s4_009.bmp
        .size   = 56,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7784, //logos/charge/level_3/s4_010.bmp
        .size   = 56,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7840, //logos/charge/level_3/s4_011.bmp
        .size   = 60,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7900, //logos/charge/level_3/s4_012.bmp
        .size   = 63,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 7963, //logos/charge/level_3/s4_013.bmp
        .size   = 63,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8026, //logos/charge/level_3/s4_014.bmp
        .size   = 62,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8088, //logos/charge/level_3/s4_015.bmp
        .size   = 63,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8151, //logos/charge/level_3/s4_016.bmp
        .size   = 67,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8218, //logos/charge/level_3/s4_017.bmp
        .size   = 68,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8286, //logos/charge/level_3/s4_018.bmp
        .size   = 65,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8351, //logos/charge/level_3/s4_019.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8421, //logos/charge/level_3/s4_020.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8491, //logos/charge/level_3/s4_021.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8561, //logos/charge/level_3/s4_022.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8631, //logos/charge/level_3/s4_023.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8701, //logos/charge/level_3/s4_024.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8771, //logos/charge/level_3/s4_025.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8841, //logos/charge/level_3/s4_026.bmp
        .size   = 70,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8911, //logos/charge/level_3/s4_027.bmp
        .size   = 67,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 8978, //logos/charge/level_3/s4_028.bmp
        .size   = 68,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9046, //logos/charge/level_3/s4_029.bmp
        .size   = 67,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9113, //logos/charge/level_3/s4_030.bmp
        .size   = 62,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9175, //logos/charge/level_3/s4_031.bmp
        .size   = 63,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9238, //logos/charge/level_3/s4_032.bmp
        .size   = 64,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9302, //logos/charge/level_3/s4_033.bmp
        .size   = 60,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9362, //logos/charge/level_3/s4_034.bmp
        .size   = 59,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9421, //logos/charge/level_3/s4_035.bmp
        .size   = 62,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9483, //logos/charge/level_3/s4_036.bmp
        .size   = 59,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9542, //logos/charge/level_3/s4_037.bmp
        .size   = 56,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9598, //logos/charge/level_3/s4_038.bmp
        .size   = 52,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9650, //logos/charge/level_3/s4_039.bmp
        .size   = 51,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9701, //logos/charge/level_3/s4_040.bmp
        .size   = 53,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9754, //logos/charge/level_3/s4_041.bmp
        .size   = 54,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9808, //logos/charge/level_3/s4_042.bmp
        .size   = 58,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9866, //logos/charge/level_3/s4_043.bmp
        .size   = 44,
        .level  = 71,
        .loaded = 0,
    },
    {
        .offset = 9910, //logos/charge/level_4/s5_001.bmp
        .size   = 44,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 9954, //logos/charge/level_4/s5_002.bmp
        .size   = 43,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 9997, //logos/charge/level_4/s5_003.bmp
        .size   = 53,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10050, //logos/charge/level_4/s5_004.bmp
        .size   = 50,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10100, //logos/charge/level_4/s5_005.bmp
        .size   = 51,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10151, //logos/charge/level_4/s5_006.bmp
        .size   = 50,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10201, //logos/charge/level_4/s5_007.bmp
        .size   = 49,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10250, //logos/charge/level_4/s5_008.bmp
        .size   = 52,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10302, //logos/charge/level_4/s5_009.bmp
        .size   = 53,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10355, //logos/charge/level_4/s5_010.bmp
        .size   = 52,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10407, //logos/charge/level_4/s5_011.bmp
        .size   = 55,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10462, //logos/charge/level_4/s5_012.bmp
        .size   = 58,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10520, //logos/charge/level_4/s5_013.bmp
        .size   = 59,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10579, //logos/charge/level_4/s5_014.bmp
        .size   = 58,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10637, //logos/charge/level_4/s5_015.bmp
        .size   = 58,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10695, //logos/charge/level_4/s5_016.bmp
        .size   = 61,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10756, //logos/charge/level_4/s5_017.bmp
        .size   = 61,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10817, //logos/charge/level_4/s5_018.bmp
        .size   = 59,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10876, //logos/charge/level_4/s5_019.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 10938, //logos/charge/level_4/s5_020.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11000, //logos/charge/level_4/s5_021.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11062, //logos/charge/level_4/s5_022.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11124, //logos/charge/level_4/s5_023.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11186, //logos/charge/level_4/s5_024.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11248, //logos/charge/level_4/s5_025.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11310, //logos/charge/level_4/s5_026.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11372, //logos/charge/level_4/s5_027.bmp
        .size   = 61,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11433, //logos/charge/level_4/s5_028.bmp
        .size   = 62,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11495, //logos/charge/level_4/s5_029.bmp
        .size   = 61,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11556, //logos/charge/level_4/s5_030.bmp
        .size   = 56,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11612, //logos/charge/level_4/s5_031.bmp
        .size   = 58,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11670, //logos/charge/level_4/s5_032.bmp
        .size   = 60,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11730, //logos/charge/level_4/s5_033.bmp
        .size   = 56,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11786, //logos/charge/level_4/s5_034.bmp
        .size   = 55,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11841, //logos/charge/level_4/s5_035.bmp
        .size   = 58,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11899, //logos/charge/level_4/s5_036.bmp
        .size   = 55,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 11954, //logos/charge/level_4/s5_037.bmp
        .size   = 50,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 12004, //logos/charge/level_4/s5_038.bmp
        .size   = 48,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 12052, //logos/charge/level_4/s5_039.bmp
        .size   = 48,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 12100, //logos/charge/level_4/s5_040.bmp
        .size   = 50,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 12150, //logos/charge/level_4/s5_041.bmp
        .size   = 51,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 12201, //logos/charge/level_4/s5_042.bmp
        .size   = 56,
        .level  = 100,
        .loaded = 0,
    },
    {
        .offset = 12257, //logos/charge/level_4/s5_043.bmp
        .size   = 42,
        .level  = 100,
        .loaded = 0,
    },
};


#endif //BMP_IMAGE_DATA_H__
