/*
 * Automatically generated by "tools/bmp_logo"
 *
 * DO NOT EDIT
 *
 */


#ifndef __BMP_CHARGE_LOGO_H__
#define __BMP_CHARGE_LOGO_H__

#define BMP_CHARGE_LOGO_WIDTH		160
#define BMP_CHARGE_LOGO_HEIGHT		96
#define BMP_CHARGE_LOGO_COLORS		31
#define BMP_CHARGE_LOGO_OFFSET		16

extern unsigned short bmp_charge_logo_palette[];
extern unsigned char bmp_charge_logo_bitmap[];

#endif /* __BMP_CHARGE_LOGO_H__ */
